### ISSUE TITLE
Bitwig doesn't forward some changes made in its parameter list to the plugin

### ISSUE THREAD

**Issue by robbert-vdh** [free-audio/interop-tracker#14]
Not quite sure what the exact reason is, but this bug involves changing a stepped parameter with minimum value of 0, a maximum value of 1, and a default value of 0, after loading a preset/state where the parameter was saved with a value of 1. Changing the parameter from 1 to 0 works as expected, but changing the parameter back from 0 to 1 doesn't send a parameter change to the plugin. Changing the parameter back from 1 to 0 sends the plugin a parameter value event for the 0 value, and after that point everything works again as expected.

To reproduce this, grab the `Crossover.clap` plugin from one of these CI page (comes in Linux, Windows, x86_64 macOS, and AArch64 macOS versions, I reproduced the issue myself on Linux):
- https://nightly.link/robbert-vdh/nih-plug/workflows/build/master for CLAP 0.26
- https://nightly.link/robbert-vdh/nih-plug/workflows/build/feature%2Fclap-next for the next branch

Then open this project: [clap-stepped-parameter-bug.tar.gz](https://github.com/free-audio/interop-tracker/files/8855943/clap-stepped-parameter-bug.tar.gz)
 
The project contains an audio track with a test tone device at -90 dB just to prevent the track from sleeping, and an instance of that Crossover plugin set to the 'LR24 (LP)' mode, which introduces the equivalent of 3072 samples of latency. Selecting the track and checking the inspector panel should confirm this: https://user-images.githubusercontent.com/748520/172464672-e4d38ffb-cede-4a08-b39a-4021217d2540.png

Changing the Type parameter at the bottom of the plugin's parameter list to 'LR24' changes the latency to 0 samples, which is expected. The bug happens when you try to change the Type parameter back to 'LR24 (LP)'. Doing so does not send a parameter value event to the plugin, and you'll also see that the reported latency is still at 0 samples. Changing the parameter back 'LR24' does send a parameter change to the plugin (you can't see this reflected anywhere), and after that point changing the parameter works as expected again.

Let me know if this wasn't clear enough!

**Comment by abique** [comment]
So I get this:
```
CLAP: ParamValue, block: 1488, time: 0, note_id: -1, port: -1, channel: -1, key: -1, value: 0.0
PluginHost: Requesting restart of audio processing
Requesting restart of processing because IO buses or latency have changed
PluginDeviceContentsNode request restart processing
Starting fade out because request restart processing
Sending ready to restart processing
PluginDeviceContents ready to restart processing
PluginHost: Ready to restart audio processing
Ready to restart processing
Applying plugin IO state
CLAP: ParamValue, block: 2171, time: 0, note_id: -1, port: -1, channel: -1, key: -1, value: 1.0
PluginHost: Requesting restart of audio processing
Requesting restart of processing because IO buses or latency have changed
PluginDeviceContentsNode request restart processing
Starting fade out because request restart processing
Sending ready to restart processing
PluginDeviceContents ready to restart processing
PluginHost: Ready to restart audio processing
Ready to restart processing
Applying plugin IO state
```

**Comment by abique** [comment]
Should be fixed in next build.

**Comment by robbert-vdh** [comment]
This still happens in 4.3.2. Confirmed this with the plugin and project I posted above, and with another plugin I was working on where I noticed that the DC filter parameter wouldn't reactivate on the first try when loading a state with the parameter enabled.

**Comment by robbert-vdh** [comment]
Video of the above:

https://user-images.githubusercontent.com/748520/179003783-ce4328f3-f324-4c20-b7d3-b07f7ef6968a.mp4

Notice how after reactivating the plugin and disabling the DC filter, the first time turning it back on again doesn't do anything.

**Comment by abique** [comment]
Fixed for bitwig 4.3.10

**Comment by robbert-vdh** [comment]
This still happens in 4.3.10 with the project/setup from the OP.

**Comment by abique** [comment]
4.3.10 is a hotfix and didn't include the changes that was staged for this version. Coming soon...

**Comment by robbert-vdh** [comment]
Awesome, this one is now indeed fixed in 4.4.1.
