### ISSUE TITLE
Bitwig 4.4 voice stack on monophonic patch crash

### ISSUE THREAD

**Issue by nakst** [free-audio/interop-tracker#48]
I'm getting a crash on the latest Bitwig in x86_64 Linux with my CLAP plugin ([Apricot](https://nakst.itch.io/apricot)) when: 
1. Load a polyphonic patch (as reported by the voice-info extension)
2. Set >1 voice stack size
3. Load a monophonic patch (as reported by the voice-info extension)
4. Hold 2 notes at the same time (I'm using the caps lock keyboard to midi)

Then the audio thread crashes.

I'm running my plugins in the "Together" mode, i.e. in a separate process to the one that crashes. It's possible my plugin has implemented one of the extensions incorrectly, but I am not sure how that could lead to the different process crashing.

I am using Bitwig Studio version 4.4.3-1 demo on Arch Linux, from https://aur.archlinux.org/packages/bitwig-studio.

**Comment by abique** [comment]
I could not reproduce the crash, but I suppose it has been fixed since it was reported.
I've spotted a bug when adding or removing modulation which I've fixed for Bitwig 5.0 Beta 7.
So please try again with that version (once it is released).

**Comment by nakst** [comment]
Is there a way to access the beta for plugin-testing-only-purposes if I don't already own Bitwig?
If not, I'll wait for the full release.

**Comment by nakst** [comment]
The crash is still occurring in the latest Bitwig beta. I have uploaded a video showing how to reproduce the problem here:

https://github.com/free-audio/interop-tracker/assets/17091026/38c937b1-c7d8-4827-978e-8d9244fa05e2

The crash happens when I press the second note using keyboard-to-MIDI.

**Comment by abique** [comment]
@nakst is it still crashing for you?

**Comment by abique** [comment]
It doesn't crash for me anymore.
If you confirm the fix, then please close the issue.

**Comment by nakst** [comment]
It's still crashing for me in Bitwig version 5.0.7.
I have attached a screenshot of the stack trace printed by GDB and the version information displays by Bitwig:
![bitwig-crash-stack-trace](https://github.com/free-audio/interop-tracker/assets/17091026/5630cc84-3499-452a-a572-a150c36da77c)
![bitwig-crash-version](https://github.com/free-audio/interop-tracker/assets/17091026/6152a9e8-211a-4113-b111-650af3a49e45)

**Comment by abique** [comment]
Oh, it is fixed on our dev branch, so it'll be fixed in 5.1.

**Comment by nakst** [comment]
I tried the 5.1 beta, but now voice stacking is not working at all in my plugins -- it behaves as if there is only one voice. Another user has also reported this issue: https://www.kvraudio.com/forum/viewtopic.php?p=8773563
Checking the note on/off events received by the plugin, it is only receiving one note event even when stacking is enabled.

**Comment by abique** [comment]
I've just tried it with apricot 1.1.12, and it seems to work well.
If you set the synth to mono, it only has one voice, so bitwig doesn't offer voice stacking in that case.
